### PR TITLE
Add Firebase

### PR DESCRIPTION
**Pull request by CalebMacdonaldBlack**

### CODE REVIEW

**Comment by thheller** [comment]
Thanks but these do not quite look correct.

Everything is pulling in the base `"firebase"` which is a bundle that contains everything. I think each should depend on `"firebase/app"` and then the appropriate `"firebase/auth"` and so on individually.

Which library uses the `cljsjs` package? If possible we should avoid pulling in the base `firebase` since that might include stuff (ie. bytes) that actually won't be used at all which can become quite big.

**Comment by CalebMacdonaldBlack** [comment]
@thheller Ahh okay, Ill see if I can get this to only include what is necessary. 
It is using this library https://github.com/cljsjs/packages/tree/master/firebase

**Comment by thheller** [comment]
Which library uses the cljsjs library? If its only in your code you can skip the cljsjs packages entirely and use `(:require ["firebase/app" :as firebase])` directly instead.

**Comment by thheller** [comment]
See this excellent firebase example: https://github.com/jacekschae/shadow-firebase

**Comment by CalebMacdonaldBlack** [comment]
This is the library that uses it https://github.com/deg/re-frame-firebase

**Comment by CalebMacdonaldBlack** [comment]
@thheller Okay I pushed changes

**Comment by thheller** [comment]
Thanks. Will include them in the next `shadow-cljs` release

**Pull request merged**
